import { defineStore } from 'pinia';
import { ref, computed } from 'vue';

export const useProductStore = defineStore('products', () => {
  const products = ref([
    { id: 1, name: 'Pin de Niña', price: 500, salePrice: null, imageUrl: new URL('../assets/img/niña.jpeg', import.meta.url).href },
    { id: 2, name: 'Pin de Nube', price: 500, salePrice: null, imageUrl: new URL('../assets/img/nube.jpeg', import.meta.url).href },
    { id: 3, name: 'Pin Gato Bus', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/gato bus.jpeg', import.meta.url).href },
    { id: 4, name: 'Pin Zuko', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/zuko.jpeg', import.meta.url).href },
    { id: 5, name: 'Pin Sin Cara Cafe', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/sin cara cafe.jpeg', import.meta.url).href },
    { id: 6, name: 'Pin Sin Cara Pocima', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/sin cara pocima.jpeg', import.meta.url).href },
    { id: 7, name: 'Pin Capibara Cuadrado', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/capibara cuadrado.jpeg', import.meta.url).href },
    { id: 8, name: 'Pin The Last of Us', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/TLOU.jpeg', import.meta.url).href },
    { id: 9, name: 'Pin Taza Slytherin', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/taza slytherin.jpeg', import.meta.url).href },
    { id: 10, name: 'Pin Sin Cara en Tina', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/sin cara en tina.jpeg', import.meta.url).href },
    { id: 11, name: 'Pin Cosa Derretida Amarilla', price: 500, salePrice: null, imageUrl: new URL('../assets/img/cosa derretida amarilla.jpeg', import.meta.url).href },
    { id: 12, name: 'Pin Capibara con Bebe', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/capibara y bebe.jpeg', import.meta.url).href },
    { id: 13, name: 'Pin Conejo Rojo', price: 500, salePrice: null, imageUrl: new URL('../assets/img/conejo rojo.jpeg', import.meta.url).href },
    { id: 14, name: 'Pin Conejo Splash', price: 500, salePrice: null, imageUrl: new URL('../assets/img/conejo splash.jpeg', import.meta.url).href },
    { id: 15, name: 'Pin Diablito con cachos y camisa de rayas', price: 500, salePrice: null, imageUrl: new URL('../assets/img/diablito con cachos y camisa de rayas.jpeg', import.meta.url).href },
    { id: 16, name: 'Pin Los Goonies', price: 500, salePrice: null, imageUrl: new URL('../assets/img/los Goonies.jpeg', import.meta.url).href },
    { id: 17, name: 'Pin Tostadora', price: 500, salePrice: null, imageUrl: new URL('../assets/img/tostadora.jpeg', import.meta.url).href },
    { id: 18, name: 'Pin Mounstrous', price: 500, salePrice: null, imageUrl: new URL('../assets/img/mounstrous.jpeg', import.meta.url).href },
    { id: 19, name: 'Pin Gordo Albert', price: 500, salePrice: null, imageUrl: new URL('../assets/img/Gordo albert.jpeg', import.meta.url).href },
    { id: 20, name: 'Pin Gato Negro Bolsita', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/gato negro bolsa.jpeg', import.meta.url).href },
    { id: 21, name: 'Pin Gato Blanco Bolsita', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/gato blanco bolsa.jpeg', import.meta.url).href },
    { id: 22, name: 'Pin Ballena con Cuerno', price: 500, salePrice: null, imageUrl: new URL('../assets/img/ballena con cuerno.jpeg', import.meta.url).href },
    { id: 23, name: 'Pin Pocima Felicidad Shrek', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/pocima shrek.jpeg', import.meta.url).href },
    { id: 24, name: 'Pin Pocima Hufflepuff', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/pocima hufflepuff.jpeg', import.meta.url).href },
    { id: 25, name: 'Pin Slytherin', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/Slytherin pocima.jpeg', import.meta.url).href },
    { id: 26, name: 'Pin Ravenclaw', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/pocima ravenclaw.jpeg', import.meta.url).href },
    { id: 27, name: 'Pin Gryffindor', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/pocima gryffindor.jpeg', import.meta.url).href },
    { id: 28, name: 'Pin Gatos en Caja de Cigarros Negra', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/gatos en cigarros caja negra.jpeg', import.meta.url).href },
    { id: 29, name: 'Pin Cigarros con Caja de Gato', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/cigarros con caja de gato.jpeg', import.meta.url).href },
    { id: 30, name: 'Pin Gato Naranja con Caja de Cigarro', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/gato naranja con caja de cigarro.jpeg', import.meta.url).href },
    { id: 31, name: 'Pin Caja de Cigarro con Gato Blanco y Naranja', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/caja cigarros gato naranja.jpeg', import.meta.url).href },
    { id: 32, name: 'Pin Los Picapiedras', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/picapiedras.jpeg', import.meta.url).href },
    { id: 33, name: 'Pin Cosmo', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/cosmo.jpeg', import.meta.url).href },
    { id: 34, name: 'Pin Wanda', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/wanda.jpeg', import.meta.url).href },
    { id: 35, name: 'Pin Dexter', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/dexter.jpeg', import.meta.url).href },
    { id: 36, name: 'Pin Dumbasses', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/dumbasses.jpeg', import.meta.url).href },
    { id: 37, name: 'Pin Wall-E x Star Wars', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/wall e x star wars.jpeg', import.meta.url).href },
    { id: 38, name: 'Pin Robin Hood', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/robin hood.jpeg', import.meta.url).href },
    { id: 39, name: 'Pin La Muerte (Meme)', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/la muerte meme.jpeg', import.meta.url).href },
    { id: 40, name: 'Pin Mapache Perfecto (Meme)', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/mapache meme.jpeg', import.meta.url).href },
    { id: 41, name: 'Pin Hipopotamo', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/hipopotamo.jpeg', import.meta.url).href },
    { id: 42, name: 'Pin Perro Blanco Family Guy', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Brian griffin.jpeg', import.meta.url).href },
    { id: 43, name: 'Pin Don Gato', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/don gato.jpeg', import.meta.url).href },
    { id: 44, name: 'Pin Mapache Dysfunctional', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/mapache disfuncional.jpeg', import.meta.url).href },
    { id: 45, name: 'Pin Recreo', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/recreo.jpeg', import.meta.url).href },
    { id: 46, name: 'Pin Aang', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/aang.jpeg', import.meta.url).href },
    { id: 47, name: 'Pin Libro 3 Gravity Falls', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/libro 3 gravity falls.jpeg', import.meta.url).href },
    { id: 48, name: 'Pin Pato Gravity Falls', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/pato gravity falls.jpeg', import.meta.url).href },
    { id: 49, name: 'Pin Bubble Tea My Melody', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Bubble tea my melody.jpeg', import.meta.url).href },
    { id: 50, name: 'Pin Bubble Tea Ponponpurin', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Bubble tea ponponpurin.jpeg', import.meta.url).href },
    { id: 51, name: 'Pin Bubble Tea Cinnamon Roll', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Bubble tea cinnamon roll.jpeg', import.meta.url).href },
    { id: 52, name: 'Pin Bubble Tea Pochaco', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Bubble tea pochaco.jpeg', import.meta.url).href },
    { id: 53, name: 'Pin Bubble Tea Hello Kitty', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Bubble tea hello kitty.jpeg', import.meta.url).href },
    { id: 54, name: 'Pin Bubble Tea Kuromi', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Bubble tea kuromi.jpeg', import.meta.url).href },
    { id: 55, name: 'Pin Gato to Talk Me', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/gato to talk me.jpeg', import.meta.url).href },
    { id: 56, name: 'Pin Mapache Caos', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/mapache chaos.jpeg', import.meta.url).href },
    { id: 57, name: 'Pin Kuromi Caldero', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/kuromi caldero.jpeg', import.meta.url).href },
    { id: 58, name: 'Pin Kuromi Vincha Lazo', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/kuromi bincha lazo.jpeg', import.meta.url).href },
    { id: 59, name: 'Pin Kuromi Bata Rosada', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/kuromi bata rosada.jpeg', import.meta.url).href },
    { id: 60, name: 'Pin Kuromi Brujita', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/kuromi brujita.jpeg', import.meta.url).href },
    { id: 61, name: 'Pin Kuromi con Batido', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/kuromi con batido.jpeg', import.meta.url).href },
    { id: 62, name: 'Pin The Mastermind', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/the mastermind.jpeg', import.meta.url).href },
    { id: 63, name: 'Pin ET', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/ET.jpeg', import.meta.url).href },
    { id: 64, name: 'Pin Dino Picapiedras', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/dino.jpeg', import.meta.url).href },
    { id: 65, name: 'Pin de Snoopy Rosado', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/de snopy rosado.jpeg', import.meta.url).href },
    { id: 66, name: 'Pin Cinnamon Roll Pijama de Gato Celeste', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/pijama cinamon roll.jpeg', import.meta.url).href },
    { id: 67, name: 'Pin Kuromi Pijama de Gato Morada', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/kuromi pijama de gato morada.jpeg', import.meta.url).href },
    { id: 68, name: 'Pin Pez Koi Blanco', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/pez koi blanco.jpeg', import.meta.url).href },
    { id: 69, name: 'Pin Pez Koi Negro', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/pez koi negro.jpeg', import.meta.url).href },
    { id: 70, name: 'Pin Dinosaurios', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/dinosaurios.jpeg', import.meta.url).href },
    { id: 71, name: 'Pin Hamster Cruz', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/hamster cruz.jpeg', import.meta.url).href },
    { id: 72, name: 'Pin Pocima de Gatos Blancos', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/pocima gatos.jpeg', import.meta.url).href },
    { id: 73, name: 'Pin Buzz', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/buzz layer.jpeg', import.meta.url).href },
    { id: 74, name: 'Pin Woody', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/woody.jpeg', import.meta.url).href },
    { id: 75, name: 'Pin Dwight', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/dwigth.jpeg', import.meta.url).href },
    { id: 76, name: 'Pin Star Wars Stormtrooper Corazon', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/star wars stormtrooper corazon.jpeg', import.meta.url).href },
    { id: 77, name: 'Pin Star Wars BB-8 Grande', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/star wars bb-8 grande.jpeg', import.meta.url).href },
    { id: 78, name: 'Pin Star Wars BB-8 Pequeño', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/star wars bb-8 pequeño.jpeg', import.meta.url).href },
    { id: 79, name: 'Pin Star Wars Arturito', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/star wars Arturito.jpeg', import.meta.url).href },
    { id: 80, name: 'Pin Star Wars Darth Vader', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/star wars darkvader.jpeg', import.meta.url).href },
    { id: 81, name: 'Pin Star Wars Cuadrado', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/star wars cuadrado.jpeg', import.meta.url).href },
    { id: 82, name: 'Pin Star Wars Torre', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/star wars torre.jpeg', import.meta.url).href },
    { id: 83, name: 'Pin Libro de Alicia', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/alicia libro.jpeg', import.meta.url).href },
    { id: 84, name: 'Pin One Piece Chopper', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/one piece Chopper.jpeg', import.meta.url).href },
    { id: 85, name: 'Pin One Piece Luffy', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/one piece Luffy.jpeg', import.meta.url).href },
    { id: 86, name: 'Pin One Piece Barco', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/barco one piece.jpeg', import.meta.url).href },
    { id: 87, name: 'Pin One Piece Fruta con Sombrero', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/one piece fruta con sombrero.jpeg', import.meta.url).href },
    { id: 88, name: 'Pin Star Wars Stormtrooper Circular', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/star wars stormtropper circular.jpeg', import.meta.url).href },
    { id: 89, name: 'Pin Star Wars Stormtrooper', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/star wars stormtropper.jpeg', import.meta.url).href },
    { id: 90, name: 'Pin Johny Bravo', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/Johny Bravo.jpeg', import.meta.url).href },
    { id: 91, name: 'Pin Cobra Kai', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/cobra kai.jpeg', import.meta.url).href },
    { id: 92, name: 'Pin Arcane Corazon', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/arcane corazon.jpeg', import.meta.url).href },
    { id: 93, name: 'Pin Arcane Dedos', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/jinx dedos.jpeg', import.meta.url).href },
    { id: 94, name: 'Pin Arcane Palabra', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/arcane.jpeg', import.meta.url).href },
    { id: 95, name: 'Pin Kimetsu no Yaiba', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/kimetsu espadas.jpeg', import.meta.url).href },
    { id: 96, name: 'Pin Harry Potter Escoba', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Coleccion con escobas.jpeg', import.meta.url).href },
    { id: 97, name: 'Pin Harry Potter Redondo', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/pin-de-ejemplo.jpg', import.meta.url).href },
    { id: 98, name: 'Pin Gato Alas Rosadas', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/gato alas moradas.jpeg', import.meta.url).href },
    { id: 99, name: 'Pin Gato Alas Verde', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/gato alas verdes.jpeg', import.meta.url).href },
    { id: 100, name: 'Pin Gato Alas Moradas', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/gato alas moradas.jpeg', import.meta.url).href },
    { id: 101, name: 'Pin Chimuelo', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/chimuelo.jpeg', import.meta.url).href },
    { id: 102, name: 'Pin Furia Luminosa', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/furia luminosa.jpeg', import.meta.url).href },
    { id: 103, name: 'Pin Harry Potter Colgante Draco', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/Draco.jpeg', import.meta.url).href },
    { id: 104, name: 'Pin Harry Potter Colgante Harry', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/HP en escoba.jpeg', import.meta.url).href },
    { id: 105, name: 'Pin Harry Potter Colgante Ron', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/Ron escoba.jpeg', import.meta.url).href },
    { id: 106, name: 'Pin Harry Potter Colgante Hermione', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/Hermione escudo.jpeg', import.meta.url).href },
    { id: 107, name: 'Pin Espada Fuego', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/espada fuego.jpeg', import.meta.url).href },
    { id: 108, name: 'Pin Espada Cruzada', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/espada caduceo.jpeg', import.meta.url).href },
    { id: 109, name: 'Pin Espada Mariposas', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/espada mariposas.jpeg', import.meta.url).href },
    { id: 110, name: 'Pin Espada Agua', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/espada agua.jpeg', import.meta.url).href },
    { id: 111, name: 'Pin Espada Amarilla y Azul', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/espada amarilla y azul.jpeg', import.meta.url).href },
    { id: 112, name: 'Pin Espada Serpientes Blanca y Negra', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/espada serpientes blanca y negra.jpeg', import.meta.url).href },
    { id: 113, name: 'Pin Espada Serpiente Grande', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/espada serpiente grande.jpeg', import.meta.url).href },
    { id: 114, name: 'Pin Espada Viento', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/espada viento.jpeg', import.meta.url).href },
    { id: 115, name: 'Pin Espada Roca', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/Coleccion rock.jpeg', import.meta.url).href },
    { id: 116, name: 'Pin Social Battery Rojo Rectangulo', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/social battery rojo rectangulo.jpeg', import.meta.url).href },
    { id: 117, name: 'Pin Social Battery Rectangular Blanca', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/sociual battery rectangular blanca.jpeg', import.meta.url).href },
    { id: 118, name: 'Pin Social Mood Arcoiris', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/social mood arcoiris.jpeg', import.meta.url).href },
    { id: 119, name: 'Pin Hora de Aventura', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/Coleccion Hora de aventura.jpeg', import.meta.url).href },
    { id: 120, name: 'Pin Escudo Howards', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/HP escudo.jpeg', import.meta.url).href },
    { id: 121, name: 'Pin Escudo Hufflepuff', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/hufflepuff.jpeg', import.meta.url).href },
    { id: 122, name: 'Pin Escudo Gryffindor', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/Gryffindor Escudo.jpeg', import.meta.url).href },
    { id: 123, name: 'Pin Escudo Ravenclaw', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/Ravenclaw escudo.jpeg', import.meta.url).href },
    { id: 124, name: 'Pin Escudo Slytherin', price: 2500, salePrice: null, imageUrl: new URL('../assets/img/Slytherin escudo.jpeg', import.meta.url).href },
    { id: 125, name: 'Pin Sombrero Grande HP', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/Sombre hp.jpeg', import.meta.url).href },
    { id: 126, name: 'Pin Corbata Hufflepuff', price: 300, salePrice: null, imageUrl: new URL('../assets/img/corbata hufflepuff.jpeg', import.meta.url).href },
    { id: 127, name: 'Pin Corbata Slytherin', price: 300, salePrice: null, imageUrl: new URL('../assets/img/corbata slytherin.jpeg', import.meta.url).href },
    { id: 128, name: 'Pin Corbata Gryffindor', price: 300, salePrice: null, imageUrl: new URL('../assets/img/corbata gryffindor.jpeg', import.meta.url).href },
    { id: 129, name: 'Pin Corbata Ravenclaw', price: 300, salePrice: null, imageUrl: new URL('../assets/img/corbata ravenclaw.jpeg', import.meta.url).href },
    { id: 130, name: 'Pin Buho con alas abiertas y carta HP', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/Buho alas abiertas hp.jpeg', import.meta.url).href },
    { id: 131, name: 'Pin Maleta HP', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/maleta hp.jpeg', import.meta.url).href },
    { id: 132, name: 'Pin Casa de HP', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/Casa hog.jpeg', import.meta.url).href },
    { id: 133, name: 'Pin Sapo Trevor HP', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Sapo hp.jpeg', import.meta.url).href },
    { id: 134, name: 'Pin Buho Hedwig HP', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/hedwig hp.jpeg', import.meta.url).href },
    { id: 135, name: 'Pin Ave con azul HP', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/ave con azul hp.jpeg', import.meta.url).href },
    { id: 136, name: 'Pin Flor Rosa', price: 500, salePrice: null, imageUrl: new URL('../assets/img/flor rosa.jpeg', import.meta.url).href },
    { id: 137, name: 'Pin Flor Rojo', price: 500, salePrice: null, imageUrl: new URL('../assets/img/flor rojo.jpeg', import.meta.url).href },
    { id: 138, name: 'Pin Flor Negro', price: 500, salePrice: null, imageUrl: new URL('../assets/img/flor negro.jpeg', import.meta.url).href },
    { id: 139, name: 'Pin Flor Morado', price: 500, salePrice: null, imageUrl: new URL('../assets/img/flor morado.jpeg', import.meta.url).href },
    { id: 140, name: 'Pin Totoros y Totoritos Caminando', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/totoros y totoritos caminando.jpeg', import.meta.url).href },
    { id: 141, name: 'Pin Bubble Tea Hora de Aventura, Verde', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Bubble tea verde.jpeg', import.meta.url).href },
    { id: 142, name: 'Pin Bubble Tea Hora de Aventura, Celeste', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Bubble tea celeste.jpeg', import.meta.url).href },
    { id: 143, name: 'Pin Bubble Tea Hora de Aventura, Rosado', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Bubble tea rosado.jpeg', import.meta.url).href },
    { id: 144, name: 'Pin Bubble Tea Hora de Aventura, Morado', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Bubble tea morado.jpeg', import.meta.url).href },
    { id: 145, name: 'Pin Bubble Tea Hora de Aventura, Azul', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Bubble tea azul.jpeg', import.meta.url).href },
    { id: 146, name: 'Pin Sanrio Peluches Ponponpurin', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/ponponpurin.jpeg', import.meta.url).href },
    { id: 147, name: 'Pin Sanrio Peluches Cinamonroll', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/cinamon roll.jpeg', import.meta.url).href },
    { id: 148, name: 'Pin Sanrio Peluches Kuromi', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/kuromi abrigo.jpeg', import.meta.url).href },
    { id: 149, name: 'Pin Sanrio Peluches Hello Kitty', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/hello kitty abrigo.jpeg', import.meta.url).href },
    { id: 150, name: 'Pin Sanrio Peluches My melody', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/My melody abrigo.jpeg', import.meta.url).href },
    { id: 151, name: 'Pin Sanrio Peluches Pochaco', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Pochaco abrigo.jpeg', import.meta.url).href },
    { id: 152, name: 'Pin Pink Floyd', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Pink floyd.jpeg', import.meta.url).href },
    { id: 153, name: 'Pin Guns N Roses', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Guns n roses.jpeg', import.meta.url).href },
    { id: 154, name: 'Pin Mötley Crüe', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Motley Crue.jpeg', import.meta.url).href },
    { id: 155, name: 'Pin Oasis', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/oasis.jpeg', import.meta.url).href },
    { id: 156, name: 'Pin Slipknot', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Sipknot.jpeg', import.meta.url).href },
    { id: 157, name: 'Pin The Beatles', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Beatles.jpeg', import.meta.url).href },
    { id: 158, name: 'Pin AC/DC', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/acdc.jpeg', import.meta.url).href },
    { id: 159, name: 'Pin KISS', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/kiss.jpeg', import.meta.url).href },
    { id: 160, name: 'Pin Miyagi-Do', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Miyagi do.jpeg', import.meta.url).href },
    { id: 161, name: 'Pin Taza The Office', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Taza the office.jpeg', import.meta.url).href },
    { id: 162, name: 'Pin Pi 3,14', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Pi.jpeg', import.meta.url).href },
    { id: 163, name: 'Pin Cosmo y Wanda', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Cosmo&wanda.jpeg', import.meta.url).href },
    { id: 164, name: 'Pin Perry el Ornitorrinco', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Perry.jpeg', import.meta.url).href },
    { id: 165, name: 'Pin Fruta One Piece Gris', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Fruta one piece gris.jpeg', import.meta.url).href },
    { id: 166, name: 'Pin Psicología Circular', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Psicologia circular.jpeg', import.meta.url).href },
    { id: 167, name: 'Pin I\'m a Psychologist', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/im a psychologist.jpeg', import.meta.url).href },
    { id: 168, name: 'Pin Psicología Mariposa', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/Mariposa psicologia.jpeg', import.meta.url).href },
    { id: 169, name: 'Pin Psicología Psych', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/Psych.jpeg', import.meta.url).href },
    { id: 170, name: 'Pin Psychology Degree', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/Psychology degree.jpeg', import.meta.url).href },
    { id: 171, name: 'Pin Mushu con Grillo', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Mushu y grillo.jpeg', import.meta.url).href },
    { id: 172, name: 'Pin Mushu Vogue', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Mushu Vogue.jpeg', import.meta.url).href },
    { id: 173, name: 'Pin Mushu Ramen', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Mushu Ramen.jpeg', import.meta.url).href },
    { id: 174, name: 'Pin Mushu con mano alzada', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Mushu mano.jpeg', import.meta.url).href },
    { id: 175, name: 'Pin Mushu con grillo y bigote largo', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Mushu con bigote.jpeg', import.meta.url).href },
    { id: 176, name: 'Pin Boo Disfrazada Monster Inc', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Boo Mounster.jpeg', import.meta.url).href },
    { id: 177, name: 'Pin Monster INC Circular', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/Mounter INC circular.jpeg', import.meta.url).href },
    { id: 178, name: 'Pin Monster Inc de pie los 3', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/Mounter INC.jpeg', import.meta.url).href },
    { id: 179, name: 'Pin Monster Inc en Puerta', price: 2000, salePrice: null, imageUrl: new URL('../assets/img/Mounter inc en puerta.jpeg', import.meta.url).href },
    { id: 180, name: 'Pin Sullivan Arrecostado', price: 1500, salePrice: null, imageUrl: new URL('../assets/img/Mounter INC arrecostado.jpeg', import.meta.url).href },
    { id: 181, name: 'Pin Piña', price: 1000, salePrice: null, imageUrl: new URL('../assets/img/piña.jpeg', import.meta.url).href }
  ]);
  
  const getProductById = computed(() => {
    return (productId) => products.value.find(prod => prod.id === Number(productId));
  });

  return { products, getProductById };
});