import { defineStore } from 'pinia';
import { ref, computed } from 'vue';

export const useProductStore = defineStore('products', () => {
  const products = ref([
    // Se han aplicado correcciones de ortografía solo en la propiedad 'name'.
    { id: 1, name: 'Pin de Niña', price: 500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/niña.jpeg', import.meta.url).href },
    { id: 2, name: 'Pin de Nube', price: 500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/nube.jpeg', import.meta.url).href },
    { id: 3, name: 'Pin Gato Bus (Totoro)', price: 1000, category: 'studio-ghibli', salePrice: null, imageUrl: new URL('../assets/img/Gato bus.jpeg', import.meta.url).href },
    { id: 4, name: 'Pin Zuko (El Avatar: la leyenda de Aang)', price: 1500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/zuko.jpeg', import.meta.url).href },
    { id: 5, name: 'Pin Sin Cara (El Viaje de Chihiro)', price: 1500, category: 'studio-ghibli', salePrice: null, imageUrl: new URL('../assets/img/Sin cara cafe.jpeg', import.meta.url).href, soldOut: true },
    { id: 6, name: 'Pin Sin Cara con Pócima (El Viaje de Chihiro)', price: 1500, category: 'studio-ghibli', salePrice: null, imageUrl: new URL('../assets/img/Sin cara pocima.jpeg', import.meta.url).href },
    { id: 7, name: 'Pin Capibara', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/capibara cuadrado.jpeg', import.meta.url).href },
    { id: 8, name: 'Pin The Last of Us', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/TLOU.jpeg', import.meta.url).href },
    { id: 9, name: 'Pin Taza Slytherin (Harry Potter)', price: 1500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/taza slytherin.jpeg', import.meta.url).href },
    { id: 10, name: 'Pin Sin Cara en Tina (El Viaje de Chihiro)', price: 2000, category: 'studio-ghibli', salePrice: null, imageUrl: new URL('../assets/img/Sin cara tina.jpeg', import.meta.url).href },
    { id: 17, name: 'Pin Capibara con Bebé', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/capibara y bebe.jpeg', import.meta.url).href },
    { id: 20, name: 'Pin Gato Negro Bolsita', price: 1000, category: 'gatos', salePrice: null, imageUrl: new URL('../assets/img/gato negro bolsa.jpeg', import.meta.url).href, soldOut: true },
    { id: 21, name: 'Pin Gato Blanco Bolsita', price: 1000, category: 'gatos', salePrice: null, imageUrl: new URL('../assets/img/gato blanco bolsa.jpeg', import.meta.url).href, soldOut: true },
    { id: 22, name: 'Pin Ballena meme', price: 500, category: 'humor', salePrice: null, imageUrl: new URL('../assets/img/ballena meme.jpeg', import.meta.url).href },
    { id: 23, name: 'Pin Pócima Felices para Siempre (Shrek)', price: 1000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/pocima shrek.jpeg', import.meta.url).href },
    { id: 24, name: 'Pin Pócima Hufflepuff (Harry Potter)', price: 1000, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Pocima hufflepuff.jpeg', import.meta.url).href },
    { id: 25, name: 'Pin Pócima Slytherin (Harry Potter)', price: 1000, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Pocima Sletheryn.jpeg', import.meta.url).href },
    { id: 26, name: 'Pin Pócima Ravenclaw (Harry Potter)', price: 1000, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/pocima ravenclaw.jpeg', import.meta.url).href },
    { id: 27, name: 'Pin Pócima Gryffindor (Harry Potter)', price: 1500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/pocima gryffindor.jpeg', import.meta.url).href },
    { id: 28, name: 'Pin Caja de Cigarro con Gatos', price: 1500, category: 'gatos', salePrice: null, imageUrl: new URL('../assets/img/caja cigarros gato negro.jpeg', import.meta.url).href },
    { id: 29, name: 'Pin Gato Naranja con Caja de Cigarros', price: 1500, category: 'gatos', salePrice: null, imageUrl: new URL('../assets/img/Gato naranja cigarros.jpeg', import.meta.url).href },
    { id: 30, name: 'Pin Ciga-Cat', price: 1500, category: 'gatos', salePrice: null, imageUrl: new URL('../assets/img/Ciga-Cat.jpeg', import.meta.url).href },
    { id: 31, name: 'Pin Caja de Cigarro con Gato Naranja', price: 1500, category: 'gatos', salePrice: null, imageUrl: new URL('../assets/img/caja cigarros gato naranja.jpeg', import.meta.url).href },
    { id: 32, name: 'Pin Los Picapiedras', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/picapiedras.jpeg', import.meta.url).href },
    { id: 33, name: 'Pin Cosmo (Los Padrinos Mágicos)', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/cosmo.jpeg', import.meta.url).href },
    { id: 34, name: 'Pin Wanda (Los Padrinos Mágicos)', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/wanda.jpeg', import.meta.url).href },
    { id: 35, name: 'Pin Dexter', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Dexter.jpeg', import.meta.url).href },
    { id: 36, name: 'Pin Dumbasses', price: 1000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Dumbasses.jpeg', import.meta.url).href },
    { id: 37, name: 'Pin Wall-E x Star Wars', price: 1500, category: 'star-wars', salePrice: null, imageUrl: new URL('../assets/img/wall e x star wars.jpeg', import.meta.url).href },
    { id: 38, name: 'Pin Robin Hood', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/robin hood.jpeg', import.meta.url).href },
    { id: 39, name: 'Pin La Muerte Arcoiris', price: 1000, category: 'humor', salePrice: null, imageUrl: new URL('../assets/img/muertes arcoiris.jpeg', import.meta.url).href },
    { id: 40, name: 'Pin Mapache', price: 1000, category: 'humor', salePrice: null, imageUrl: new URL('../assets/img/mapache meme.jpeg', import.meta.url).href },
    { id: 41, name: 'Pin Hipopótamo', price: 1000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Hipopotamo bebé.jpeg', import.meta.url).href },
    { id: 42, name: 'Pin Brian Griffin (Family Guy)', price: 1500, category: 'humor', salePrice: null, imageUrl: new URL('../assets/img/brian griffin.jpeg', import.meta.url).href },
    { id: 43, name: 'Pin Don Gato', price: 1500, category: 'gatos', salePrice: null, imageUrl: new URL('../assets/img/don gato.jpeg', import.meta.url).href },
    { id: 44, name: 'Pin Mapache Dysfunctional', price: 1500, category: 'humor', salePrice: null, imageUrl: new URL('../assets/img/mapache disfuncional.jpeg', import.meta.url).href },
    { id: 45, name: 'Pin Recreo', price: 2000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Recreo.jpeg', import.meta.url).href },
    { id: 46, name: 'Pin Aang (El Avatar: la leyenda de Aang)', price: 2000, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/aang.jpeg', import.meta.url).href },
    { id: 47, name: 'Pin Libro 3 (Gravity Falls)', price: 2000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Libro 3.jpeg', import.meta.url).href },
    { id: 48, name: 'Pin Pato (Gravity Falls)', price: 2000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Pato.jpeg', import.meta.url).href },
    { id: 49, name: 'Pin Bubble Tea-My Melody (Sanrio)', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Bubble tea my melody.jpeg', import.meta.url).href },
    { id: 50, name: 'Pin Bubble Tea-Pompompurin (Sanrio)', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Bubble tea pompompuri.jpeg', import.meta.url).href },
    { id: 51, name: 'Pin Bubble Tea-Cinnamoroll (Sanrio)', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Bubble tea cinamonroll.jpeg', import.meta.url).href },
    { id: 52, name: 'Pin Bubble Tea-Pochacco (Sanrio)', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Bubble tea pochacco.jpeg', import.meta.url).href },
    { id: 53, name: 'Pin Bubble Tea-Hello Kitty (Sanrio)', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Bubble tea hello kitty.jpeg', import.meta.url).href },
    { id: 54, name: 'Pin Bubble Tea-Kuromi (Sanrio)', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Bubble tea Kuromi.jpeg', import.meta.url).href },
    { id: 55, name: 'Pin Gato No Talk Me', price: 1500, category: 'gatos', salePrice: null, imageUrl: new URL('../assets/img/gato naranja no talk me.jpeg', import.meta.url).href },
    { id: 56, name: 'Pin Mapache Caos', price: 1000, category: 'humor', salePrice: null, imageUrl: new URL('../assets/img/mapache chaos.jpeg', import.meta.url).href },
    { id: 57, name: 'Pin Kuromi Caldero', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Kuromi caldero.jpeg', import.meta.url).href },
    { id: 58, name: 'Pin Kuromi Vincha Lazo', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/kuromi vincha.jpeg', import.meta.url).href },
    { id: 59, name: 'Pin Kuromi Bata Rosada', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Kuromi bata.jpeg', import.meta.url).href },
    { id: 61, name: 'Pin Kuromi con Batido', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Kuromi batido.jpeg', import.meta.url).href },
    { id: 62, name: 'Pin The Mastermind Ajedrez', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/the mastermind.jpeg', import.meta.url).href },
    { id: 63, name: 'Pin ET', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/et.jpeg', import.meta.url).href },
    { id: 64, name: 'Pin Dino Picapiedras', price: 1000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/dino.jpeg', import.meta.url).href },
    { id: 65, name: 'Pin Coraje, el Perro Cobarde', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/coraje.jpeg', import.meta.url).href },
    { id: 66, name: 'Pin Cinnamonroll Pijama de Gato', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/pijama cinamonroll.jpeg', import.meta.url).href },
    { id: 67, name: 'Pin Kuromi Pijama de Gato', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/kuromi abrigo.jpeg', import.meta.url).href },
    { id: 68, name: 'Pin Pez Koi Blanco', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/koi blanco.jpeg', import.meta.url).href },
    { id: 69, name: 'Pin Pez Koi Negro', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/koi negro.jpeg', import.meta.url).href },
    { id: 70, name: 'Pin Dinosaurios (En Busca del Valle Encantado)', price: 1000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Dinosaurios.jpeg', import.meta.url).href },
    { id: 71, name: 'Pin Hámster Cruz', price: 1500, category: 'humor', salePrice: null, imageUrl: new URL('../assets/img/hamster cruz.jpeg', import.meta.url).href },
    { id: 72, name: 'Pin Pócima de Gatos Blancos', price: 1500, category: 'gatos', salePrice: null, imageUrl: new URL('../assets/img/pocima gatos.jpeg', import.meta.url).href },
    { id: 73, name: 'Pin Buzz (Toy Story)', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/buzz layer.jpeg', import.meta.url).href },
    { id: 74, name: 'Pin Woody (Toy Story)', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/woody.jpeg', import.meta.url).href },
    { id: 75, name: 'Pin Dwight (The Office)', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/dwigth.jpeg', import.meta.url).href },
    { id: 76, name: 'Stormtrooper Corazón (Star Wars)', price: 2000, category: 'star-wars', salePrice: null, imageUrl: new URL('../assets/img/Stormtrooper Corazon.jpeg', import.meta.url).href },
    { id: 77, name: 'Pin BB-8 Grande (Star Wars)', price: 2000, category: 'star-wars', salePrice: null, imageUrl: new URL('../assets/img/star wars bb-8 grande.jpeg', import.meta.url).href },
    { id: 78, name: 'Pin BB-8 Pequeño (Star Wars)', price: 1000, category: 'star-wars', salePrice: null, imageUrl: new URL('../assets/img/star wars bb-8 pequeño.jpeg', import.meta.url).href },
    { id: 79, name: 'Pin R2-D2 (Star Wars)', price: 1500, category: 'star-wars', salePrice: null, imageUrl: new URL('../assets/img/R2-B2.jpeg', import.meta.url).href },
    { id: 80, name: 'Pin Darth Vader (Star Wars)', price: 1500, category: 'star-wars', salePrice: null, imageUrl: new URL('../assets/img/star wars darkvader.jpeg', import.meta.url).href },
    { id: 81, name: 'Pin R2-D2 Cuadrado (Star Wars)', price: 1500, category: 'star-wars', salePrice: null, imageUrl: new URL('../assets/img/r2d2 cuadrado.jpeg', import.meta.url).href },
    { id: 82, name: 'Pin Torre de Star Wars', price: 2000, category: 'star-wars', salePrice: null, imageUrl: new URL('../assets/img/star wars torre.jpeg', import.meta.url).href },
    { id: 83, name: 'Pin Libro de Alicia', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/alicia libro.jpeg', import.meta.url).href },
    { id: 84, name: 'Pin Tony Tony Chopper (One Piece)', price: 1500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/tony op.jpeg', import.meta.url).href },
    { id: 86, name: 'Pin Barco (One Piece)', price: 2000, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/barco one piece.jpeg', import.meta.url).href },
    { id: 87, name: 'Pin Fruta Gomu Gomu (One Piece)', price: 2500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/Gomu gomu.jpeg', import.meta.url).href, soldOut: true },
    { id: 88, name: 'Pin Stormtrooper Circular (Star Wars)', price: 1500, category: 'star-wars', salePrice: null, imageUrl: new URL('../assets/img/starwar circular.jpeg', import.meta.url).href },
    { id: 89, name: 'Pin Stormtrooper Grande (Star Wars)', price: 1500, category: 'star-wars', salePrice: null, imageUrl: new URL('../assets/img/starwars grande.jpeg', import.meta.url).href },
    { id: 90, name: 'Pin Johnny Bravo', price: 1000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/JB.jpeg', import.meta.url).href },
    { id: 91, name: 'Pin Cobra Kai', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/cobra kai.jpeg', import.meta.url).href },
    { id: 92, name: 'Pin Jinx Corazón (Arcane)', price: 2000, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/jinx corazon.jpeg', import.meta.url).href },
    { id: 93, name: 'Pin Jinx (Arcane)', price: 2000, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/jinx dedos.jpeg', import.meta.url).href },
    { id: 94, name: 'Pin Jinx Was Here (Arcane)', price: 1500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/jinx was here.jpeg', import.meta.url).href },
    { id: 95, name: 'Pin Zenitsu y Nezuko (Demon Slayer)', price: 2000, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/kimetsu personajes.jpeg', import.meta.url).href },
    { id: 96, name: 'Pin Harry Potter Escoba', price: 1500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/hp escoba guindado.jpeg', import.meta.url).href },
    { id: 97, name: 'Pin Harry Potter y Castillo de Hogwarts', price: 1500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/HP Castillo.jpeg', import.meta.url).href },
    { id: 100, name: 'Pin Gato Alas Moradas', price: 1500, category: 'gatos', salePrice: null, imageUrl: new URL('../assets/img/gato alas moradas.jpeg', import.meta.url).href },
    { id: 103, name: 'Pin Draco Colgante (Harry Potter)', price: 2500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Draco escoba.jpeg', import.meta.url).href },
    { id: 104, name: 'Pin Harry Colgante (Harry Potter)', price: 2500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/HP en escoba.jpeg', import.meta.url).href },
    { id: 105, name: 'Pin Ron Colgante (Harry Potter)', price: 2500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Ron escoba.jpeg', import.meta.url).href },
    { id: 106, name: 'Pin Hermione Colgante (Harry Potter)', price: 2500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Hermione escoba.jpeg', import.meta.url).href },
    { id: 107, name: 'Pin Espada Rengoku (Demon Slayer)', price: 2500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/espada Rengoku.jpeg', import.meta.url).href },
    { id: 108, name: 'Pin Espada Inosuke (Demon Slayer)', price: 2500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/espada Inosuke.jpeg', import.meta.url).href },
    { id: 109, name: 'Pin Espada Shinobu (Demon Slayer)', price: 2500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/espada Shinobu.jpeg', import.meta.url).href },
    { id: 110, name: 'Pin Espada Tomioka (Demon Slayer)', price: 2500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/espada agua.jpeg', import.meta.url).href },
    { id: 111, name: 'Pin Espada Zenitsu (Demon Slayer)', price: 2500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/espada Zenitsu.jpeg', import.meta.url).href },
    { id: 112, name: 'Pin Espada (Demon Slayer)', price: 2500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/Espada (Demon Slayer).jpeg', import.meta.url).href },
    { id: 113, name: 'Pin Espada Obanai (Demon Slayer)', price: 2500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/Espada Obanai.jpeg', import.meta.url).href },
    { id: 114, name: 'Pin Espada Sanemi (Demon Slayer)', price: 2500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/espada Sanemi.jpeg', import.meta.url).href },
    { id: 115, name: 'Pin Espada Gyomei (Demon Slayer)', price: 2500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/espada Gyomei.jpeg', import.meta.url).href },
    { id: 116, name: 'Pin Social Battery', price: 2500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/social battery rojo rectangulo.jpeg', import.meta.url).href },
    { id: 118, name: 'Pin Social Mood Arcoiris', price: 2500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/social mood arcoiris.jpeg', import.meta.url).href },
    { id: 119, name: 'Pin Hora de Aventura', price: 2500, category: 'hora-de-aventura', salePrice: null, imageUrl: new URL('../assets/img/Hora de Aventura.jpeg', import.meta.url).href },
     { id: 120, name: 'Pin Escudo Hogwarts (Harry Potter)', price: 2500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Escudo hogwarts.jpeg', import.meta.url).href, soldOut: true },{ id: 121, name: 'Pin Escudo Hufflepuff (Harry Potter)', price: 2500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/hufflepuff escudo.jpeg', import.meta.url).href },
    { id: 122, name: 'Pin Escudo Gryffindor (Harry Potter)', price: 2500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Gryffindor escudo.jpeg', import.meta.url).href, soldOut: true },
    { id: 123, name: 'Pin Escudo Ravenclaw (Harry Potter)', price: 2500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Ravenclaw escudo.jpeg', import.meta.url).href },
    { id: 124, name: 'Pin Escudo Slytherin (Harry Potter)', price: 2500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Slytherin escudo.jpeg', import.meta.url).href },
    { id: 125, name: 'Pin Sombrero (Harry Potter)', price: 1000, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Sombre hp.jpeg', import.meta.url).href },
    { id: 126, name: 'Pin Corbata Hufflepuff (Harry Potter)', price: 300, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/corbata hufflepuff.jpeg', import.meta.url).href },
    { id: 127, name: 'Pin Corbata Slytherin (Harry Potter)', price: 300, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/corbata slytherin.jpeg', import.meta.url).href },
    { id: 128, name: 'Pin Corbata Gryffindor (Harry Potter)', price: 300, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/corbata gryfffindor.jpeg', import.meta.url).href },
    { id: 129, name: 'Pin Corbata Ravenclaw (Harry Potter)', price: 300, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/corbata ravenclaw.jpeg', import.meta.url).href },
    { id: 130, name: 'Pin Búho (Harry Potter)', price: 1000, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Buho alas abiertas hp.jpeg', import.meta.url).href },
    { id: 131, name: 'Pin Maleta (Harry Potter)', price: 1500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/maleta hp.jpeg', import.meta.url).href },
    { id: 132, name: 'Pin Casa (Harry Potter)', price: 1000, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Casa hp.jpeg', import.meta.url).href },
    { id: 133, name: 'Pin Trevor (Harry Potter)', price: 1500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Sapo hp.jpeg', import.meta.url).href },
    { id: 134, name: 'Pin Hedwig (Harry Potter)', price: 1500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/hedwig hp.jpeg', import.meta.url).href },
    { id: 135, name: 'Pin Diadema Ravenclaw (Harry Potter)', price: 1500, category: 'harry-potter', salePrice: null, imageUrl: new URL('../assets/img/Diadema ravenclaw.jpeg', import.meta.url).href },
    { id: 136, name: 'Pin Flor Rosa', price: 500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/flor rosa.jpeg', import.meta.url).href },
    { id: 137, name: 'Pin Flor Rojo', price: 500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/flor roja.jpeg', import.meta.url).href },
    { id: 138, name: 'Pin Flor Negro', price: 500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/flor negra.jpeg', import.meta.url).href },
    { id: 139, name: 'Pin Flor Morado', price: 500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/flor azul.jpeg', import.meta.url).href },
    { id: 140, name: 'Pin Totoro', price: 1500, category: 'studio-ghibli', salePrice: null, imageUrl: new URL('../assets/img/totoro.jpeg', import.meta.url).href },
    { id: 141, name: 'Pin Bubble Tea-BMO (Hora de Aventura)', price: 1500, category: 'hora-de-aventura', salePrice: null, imageUrl: new URL('../assets/img/bubble tea verde.jpeg', import.meta.url).href },
    { id: 142, name: 'Pin Bubble Tea-Finn (Hora de Aventura)', price: 1500, category: 'hora-de-aventura', salePrice: null, imageUrl: new URL('../assets/img/bubble tea celeste.jpeg', import.meta.url).href },
    { id: 143, name: 'Pin Bubble Tea-Dulce Princesa (Hora de Aventura)', price: 1500, category: 'hora-de-aventura', salePrice: null, imageUrl: new URL('../assets/img/bubble tea rosado.jpeg', import.meta.url).href },
    { id: 144, name: 'Pin Bubble Tea-Princesa Grumosa (Hora de Aventura)', price: 1500, category: 'hora-de-aventura', salePrice: null, imageUrl: new URL('../assets/img/bubble tea morado.jpeg', import.meta.url).href },
    { id: 145, name: 'Pin Bubble Tea-Marceline (Hora de Aventura)', price: 1500, category: 'hora-de-aventura', salePrice: null, imageUrl: new URL('../assets/img/Bublle tea azul.jpeg', import.meta.url).href },
    { id: 146, name: 'Pin Peluche Pompompurin (Sanrio)', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Ponponpurin abrigo.jpeg', import.meta.url).href },
    { id: 147, name: 'Pin Peluche Cinnamoroll (Sanrio)', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Cinamon roll abrigo.jpeg', import.meta.url).href },
    { id: 148, name: 'Pin Peluche Kuromi (Sanrio)', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/kuromi abrigoo.jpeg', import.meta.url).href },
    { id: 149, name: 'Pin Peluche Hello Kitty (Sanrio)', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Hello kiitty abrigo.jpeg', import.meta.url).href },
    { id: 150, name: 'Pin Peluche My melody (Sanrio)', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/My melody abrigo.jpeg', import.meta.url).href },
    { id: 151, name: 'Pin Peluche Pochacco (Sanrio)', price: 1500, category: 'sanrio', salePrice: null, imageUrl: new URL('../assets/img/Pochaco abrigo.jpeg', import.meta.url).href },
    { id: 152, name: 'Pin Pink Floyd', price: 1500, category: 'musica', salePrice: null, imageUrl: new URL('../assets/img/Pink floyd.jpeg', import.meta.url).href },
    { id: 153, name: 'Pin Guns N Roses', price: 1500, category: 'musica', salePrice: null, imageUrl: new URL('../assets/img/Guns n roses.jpeg', import.meta.url).href },
    { id: 154, name: 'Pin Mötley Crüe', price: 1500, category: 'musica', salePrice: null, imageUrl: new URL('../assets/img/Montley Crue.jpeg', import.meta.url).href },
    { id: 155, name: 'Pin Oasis', price: 1500, category: 'musica', salePrice: null, imageUrl: new URL('../assets/img/oasis.jpeg', import.meta.url).href },
    { id: 156, name: 'Pin Slipknot', price: 1500, category: 'musica', salePrice: null, imageUrl: new URL('../assets/img/Slipknot.jpeg', import.meta.url).href },
    { id: 157, name: 'Pin The Beatles', price: 1500, category: 'musica', salePrice: null, imageUrl: new URL('../assets/img/Beatles.jpeg', import.meta.url).href },
    { id: 158, name: 'Pin AC/DC', price: 1500, category: 'musica', salePrice: null, imageUrl: new URL('../assets/img/acdc.jpeg', import.meta.url).href },
    { id: 159, name: 'Pin KISS', price: 1500, category: 'musica', salePrice: null, imageUrl: new URL('../assets/img/kiss.jpeg', import.meta.url).href },
    { id: 160, name: 'Pin Miyagi-Do', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Miyagi do.jpeg', import.meta.url).href },
    { id: 161, name: 'Pin Taza The Office', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Taza the office.jpeg', import.meta.url).href },
    { id: 162, name: 'Pin Pi π', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Pi.jpeg', import.meta.url).href },
    { id: 163, name: 'Pin Cosmocon', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Cosmocon.jpeg', import.meta.url).href, soldOut: true },
    { id: 164, name: 'Pin Perry el Ornitorrinco', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Perry.jpeg', import.meta.url).href },
    { id: 165, name: 'Pin Fruta (One Piece)', price: 1500, category: 'anime', salePrice: null, imageUrl: new URL('../assets/img/Fruta one piece gris.jpeg', import.meta.url).href },
    { id: 166, name: 'Pin Psicología Circular', price: 1500, category: 'psicologia', salePrice: null, imageUrl: new URL('../assets/img/Psicologia.jpeg', import.meta.url).href },
    { id: 167, name: 'Pin I\'m a Psychologist', price: 1000, category: 'psicologia', salePrice: null, imageUrl: new URL('../assets/img/im a psychologist.jpeg', import.meta.url).href },
    { id: 168, name: 'Pin Psicología Mariposa', price: 1000, category: 'psicologia', salePrice: null, imageUrl: new URL('../assets/img/Mariposa psicologia.jpeg', import.meta.url).href },
    { id: 169, name: 'Pin Psicología Psych', price: 1000, category: 'psicologia', salePrice: null, imageUrl: new URL('../assets/img/Psych.jpeg', import.meta.url).href },
    { id: 170, name: 'Pin Psychology Degree', price: 1000, category: 'psicologia', salePrice: null, imageUrl: new URL('../assets/img/Psychology degree.jpeg', import.meta.url).href },
    { id: 171, name: 'Pin Mushu con Grillo', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Mushu y grillo.jpeg', import.meta.url).href },
    { id: 172, name: 'Pin Mushu Vogue', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Mushu Vogue.jpeg', import.meta.url).href },
    { id: 173, name: 'Pin Mushu Ramen', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Mushu Ramen.jpeg', import.meta.url).href },
    { id: 174, name: 'Pin Mushu', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Musho mano.jpeg', import.meta.url).href },
    { id: 175, name: 'Pin Mushu con grillo', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Mushu con bigotes y grillo.jpeg', import.meta.url).href },
    { id: 176, name: 'Pin Boo (Monsters, Inc.)', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Boo Mounster INC.jpeg', import.meta.url).href },
    { id: 177, name: 'Pin Monsters, Inc.', price: 2000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Mounster INC.jpeg', import.meta.url).href },
    { id: 178, name: 'Pin Monsters, Inc.', price: 2000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Mounster INC circular.jpeg', import.meta.url).href },
    { id: 179, name: 'Pin Puerta Monster, Inc.', price: 2000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Mounster INC puerta.jpeg', import.meta.url).href },
    { id: 180, name: 'Pin Mike y Sullivan (Monsters, Inc.)', price: 1500, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/Mounster INC arrecostados.jpeg', import.meta.url).href, soldOut: true },
    { id: 181, name: 'Pin Piña', price: 1000, category: 'otros', salePrice: null, imageUrl: new URL('../assets/img/piña.jpeg', import.meta.url).href }
  ]);
  
  const getProductById = computed(() => {
    return (productId) => products.value.find(prod => prod.id === Number(productId));
  });

  return { products, getProductById };
});